// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace DisplayCardCssNamespace {
    export interface IDisplayCardCss {
        textEllipsis: string;
        videoActionDiv: string;
    }
}

declare const DisplayCardCssModule: DisplayCardCssNamespace.IDisplayCardCss;

export = DisplayCardCssModule;
