// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace PlaylistCardCssNamespace {
    export interface IPlaylistCardCss {
        playlistButtonActive: string;
        playlistCard: string;
        playlistCardButton: string;
        playlistCardInfo: string;
        playlistIcon: string;
        playlistInfo: string;
        playlistVideos: string;
        playlistVideosExpanded: string;
    }
}

declare const PlaylistCardCssModule: PlaylistCardCssNamespace.IPlaylistCardCss;

export = PlaylistCardCssModule;
