// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace VideoCardCssNamespace {
    export interface IVideoCardCss {
        textEllipsis: string;
        videoCard: string;
        videoCardButton: string;
        videoDuration: string;
        videoIcon: string;
        videoIconPreview: string;
        videoInfo: string;
        videoPreview: string;
        videoPreviewOpen: string;
    }
}

declare const VideoCardCssModule: VideoCardCssNamespace.IVideoCardCss;

export = VideoCardCssModule;
