// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace BottomBarCssNamespace {
    export interface IBottomBarCss {
        BottomBar: string;
        QueueContainer: string;
        bottomMiddleActions: string;
        bottomQueueButton: string;
        bottomRightActions: string;
        bottomVideoIcon: string;
        bottomVideoInfo: string;
        bottomVideoInfoFull: string;
    }
}

declare const BottomBarCssModule: BottomBarCssNamespace.IBottomBarCss;

export = BottomBarCssModule;
