// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace SidePanelCssNamespace {
    export interface ISidePanelCss {
        sidebarBody: string;
        sidebarContainer: string;
        sidebarContainerExpanded: string;
        sidebarTabBody: string;
        sidebarTabClose: string;
        sidebarTabIcon: string;
        sidebarTabIconDiv: string;
        sidebarTabSelected: string;
        sidebarTabs: string;
        sidebarTabsExpanded: string;
    }
}

declare const SidePanelCssModule: SidePanelCssNamespace.ISidePanelCss;

export = SidePanelCssModule;
