// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        playButton: string;
        progress: string;
        room: string;
        sidePanel: string;
        splitPane: string;
        videoDiv: string;
        videoPanel: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
