// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        AdminName: string;
        EditCard: string;
        ModalBox: string;
        NonexistantRoom: string;
        PageRoot: string;
        QueueContainer: string;
        RoomTitleBar: string;
        UserRow: string;
        UserRowTitle: string;
        centerTooltipChild: string;
        playButton: string;
        progress: string;
        removeAllButton: string;
        scrollBox: string;
        settingButton: string;
        sidePanel: string;
        sidePanelTabBody: string;
        splitPane: string;
        textEllipsis: string;
        videoDiv: string;
        videoPanel: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
