// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        AdminName: string;
        BottomBar: string;
        EditCard: string;
        ModalBox: string;
        PageRoot: string;
        QueueActionDiv: string;
        QueueCard: string;
        QueueCardInfo: string;
        QueueContainer: string;
        QueueExpandedTitle: string;
        QueueIcon: string;
        QueueInfo: string;
        QueueVideos: string;
        QueueVideosExpanded: string;
        SettingContainer: string;
        UserRow: string;
        UserRowTitle: string;
        VideoCardButton: string;
        VideoDuration: string;
        bottomMiddleActions: string;
        bottomRightActions: string;
        bottomVideoIcon: string;
        bottomVideoInfo: string;
        bottomVideoInfoFull: string;
        centerTooltipChild: string;
        playButton: string;
        progress: string;
        scrollBox: string;
        searchDiv: string;
        searchPanel: string;
        settingButton: string;
        settingRemoveIcon: string;
        settingTrimField: string;
        settingTrimLabel: string;
        sidePanel: string;
        sidePanelTabBody: string;
        splitPane: string;
        textEllipsis: string;
        videoDiv: string;
        videoPanel: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
