// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace EditModalCssNamespace {
    export interface IEditModalCss {
        editCard: string;
        editContainer: string;
        editList: string;
        editTitle: string;
        removeAllButton: string;
    }
}

declare const EditModalCssModule: EditModalCssNamespace.IEditModalCss;

export = EditModalCssModule;
