// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace QueuePanelCssNamespace {
    export interface IQueuePanelCss {
        queueContainer: string;
        queueTabBody: string;
        scrollBox: string;
        searchDiv: string;
    }
}

declare const QueuePanelCssModule: QueuePanelCssNamespace.IQueuePanelCss;

export = QueuePanelCssModule;
