// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace SettingsPanelCssNamespace {
    export interface ISettingsPanelCss {
        centerTooltipChild: string;
        settingContainer: string;
        settingFullWidth: string;
        settingRemoveIcon: string;
        settingTrimField: string;
        settingTrimLabel: string;
        settingUserRow: string;
    }
}

declare const SettingsPanelCssModule: SettingsPanelCssNamespace.ISettingsPanelCss;

export = SettingsPanelCssModule;
