// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace VideoPanelCssNamespace {
    export interface IVideoPanelCss {
        PlaylistCardButton: string;
        QueueActionDiv: string;
        QueueCard: string;
        QueueCardInfo: string;
        QueueExpandedTitle: string;
        QueueIcon: string;
        QueueInfo: string;
        QueueVideos: string;
        QueueVideosExpanded: string;
        VideoCardButton: string;
        VideoDuration: string;
    }
}

declare const VideoPanelCssModule: VideoPanelCssNamespace.IVideoPanelCss;

export = VideoPanelCssModule;
