// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace RoomCardCssNamespace {
    export interface IRoomCardCss {
        RoomCard: string;
        RoomCardPreview: string;
        RoomCardTitle: string;
    }
}

declare const RoomCardCssModule: RoomCardCssNamespace.IRoomCardCss;

export = RoomCardCssModule;
