// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace HeaderCssNamespace {
    export interface IHeaderCss {
        active: string;
        header: string;
        headerNav: string;
        headerRight: string;
        headerUserIcon: string;
        headerWatch: string;
    }
}

declare const HeaderCssModule: HeaderCssNamespace.IHeaderCss;

export = HeaderCssModule;
