// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace LoadingStyleCssNamespace {
    export interface ILoadingStyleCss {
        blockLoader: string;
        bounce1: string;
        bounce2: string;
        dotLoader: string;
        rect2: string;
        rect3: string;
        rect4: string;
        rect5: string;
        "sk-bouncedelay": string;
        "sk-stretchdelay": string;
    }
}

declare const LoadingStyleCssModule: LoadingStyleCssNamespace.ILoadingStyleCss;

export = LoadingStyleCssModule;
