// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace ModalCssNamespace {
    export interface IModalCss {
        ModalCancel: string;
        ModalOverlay: string;
    }
}

declare const ModalCssModule: ModalCssNamespace.IModalCss;

export = ModalCssModule;
