// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace NotificationCssNamespace {
    export interface INotificationCss {
        NotificationBackground: string;
        NotificationText: string;
        notificationError: string;
        notificationHide: string;
        notificationInfo: string;
        notificationLoading: string;
    }
}

declare const NotificationCssModule: NotificationCssNamespace.INotificationCss;

export = NotificationCssModule;
