// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        ModalBackground: string;
        PlaylistCard: string;
        PlaylistCardInfo: string;
        PlaylistIcon: string;
        PlaylistInfo: string;
        PlaylistVideos: string;
        PlaylistVideosExpanded: string;
        VideoActionDiv: string;
        VideoCard: string;
        VideoCardButton: string;
        VideoIcon: string;
        VideoInfo: string;
        active: string;
        header: string;
        headerNav: string;
        headerRight: string;
        headerUserIcon: string;
        textEllipsis: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
