// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        DropdownBackdrop: string;
        DropdownContainer: string;
        DropdownOption: string;
        VolumeBox: string;
        VolumeSlider: string;
        centerTooltipChild: string;
        popupTooltip: string;
        textEllipsis: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
